// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects whether a thread uses a caller-chosen model or lets Codex choose a
 * catalog-backed model for each user turn.
 *
 * `Auto` is a local routing mode. It is never a model identifier sent to a
 * model provider.
 */
export type ModelSelectionMode = "manual" | "auto";
